# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LinkedINLogin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'LinkedinSwift'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'AlamofireObjectMapper', '~> 5.0'

  # Pods for LinkedINLogin

end
